"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 5.0.3.
"""

from pathlib import Path
from dotenv import load_dotenv   # ✅ 반드시 필요
import os

# ==============================
# BASE DIR
# ==============================
# 프로젝트의 루트 디렉토리(config/settings.py가 있는 디렉토리의 부모 디렉토리)를 나타냅니다.
# 다른 파일 경로를 설정할 때 기준점으로 사용됩니다.
BASE_DIR = Path(__file__).resolve().parent.parent

# ==============================
# ENV LOAD
# ==============================
# 'dotenv' 라이브러리를 사용하여 .env 파일(일반적으로 BASE_DIR 아래에 위치)의 환경 변수를 로드합니다.
# **동작 원리:**
# 1. load_dotenv() 함수가 BASE_DIR/.env 파일을 읽습니다.
# 2. 파일 내의 `KEY=VALUE` 형식의 데이터를 os.environ 딕셔너리에 추가하여,
#    파이썬 코드 내에서 `os.getenv('KEY')`로 접근할 수 있게 만듭니다.
# 3. `override=True`는 이미 설정된 환경 변수도 .env 파일의 값으로 덮어쓰도록 합니다.
load_dotenv(dotenv_path=str(BASE_DIR / ".env"), override=True)

# ==============================
# SECURITY
# ==============================
# Django의 보안 및 암호화에 사용되는 시크릿 키입니다. 매우 중요합니다.
# **동작 원리:**
# - 세션 데이터 암호화, CSRF 토큰 생성, 쿠키 서명 등 다양한 보안 관련 작업에 사용됩니다.
# - 환경 변수(SECRET_KEY)에서 로드하여 실제 키를 코드에 노출하지 않도록 합니다.
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-temp-key" # 환경 변수가 없을 때 임시로 사용되는 값 (실제 운영 환경에서는 사용 금지)
)

# 디버그 모드 활성화/비활성화 설정입니다.
# **동작 원리:**
# - True: 자세한 에러 페이지 표시, 데이터베이스 쿼리 로깅, 파일 변경 시 자동 서버 재시작 등 개발 친화적 기능을 활성화합니다.
# - False: 에러 발생 시 일반적인 500 에러 페이지 표시 (보안 향상), 정적 파일 처리 방식 변경 (STATIC_ROOT 사용).
DEBUG = True

# Django 서버에 접근을 허용할 호스트 주소(도메인, IP) 목록입니다.
# **동작 원리:**
# - DEBUG=False 일 때, 요청의 Host 헤더가 이 목록에 없으면 400 Bad Request 에러를 반환하여 호스트 헤더 공격(Host header attacks)을 방지합니다.
ALLOWED_HOSTS = []

# ==============================
# APPLICATIONS
# ==============================
# 프로젝트에 설치된 Django 앱 목록입니다.
# **동작 원리:**
# - Django가 서버 시작 시 이 목록을 순회하며 앱의 모델, 템플릿 태그, 관리자 페이지 등을 로드하고 준비합니다.
# - 'django.contrib.staticfiles': 정적 파일(CSS, JS, 이미지)을 관리하는 데 필수입니다.
DJANGO_APPS = [
    'django.contrib.admin',        # Django 관리자 인터페이스
    'django.contrib.auth',         # 인증 시스템 (사용자, 그룹, 권한)
    'django.contrib.contenttypes', # 모델과 관련된 다양한 기능을 제공 (FK, Generic Relations 등)
    'django.contrib.sessions',     # 세션 프레임워크 (세션 데이터 저장 및 로드)
    'django.contrib.messages',     # 메시지 프레임워크 (일회성 알림 메시지)
    'django.contrib.staticfiles',  # 🔥 admin static 필수: 정적 파일 관리
]

OWN_APPS = [
    'bookmark', # 사용자 정의 앱
]

THIRD_PARTY_APPS = [
    # 추후 외부 라이브러리(ex: django-rest-framework, django-allauth) 추가 공간
]

INSTALLED_APPS = DJANGO_APPS + OWN_APPS + THIRD_PARTY_APPS

# ==============================
# MIDDLEWARE
# ==============================
# 요청(Request)과 응답(Response) 사이에서 실행되는 클래스들의 목록입니다.
# **동작 원리:** 
# 1. Request가 들어오면, MIDDLEWARE 목록을 **순서대로** 위에서 아래로 통과하며 처리됩니다.
# 2. Response가 나가면, MIDDLEWARE 목록을 **역순으로** 아래서 위로 통과하며 처리됩니다.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',     # 보안 관련 헤더 설정 (XFrameOptions, ContentSecurityPolicy 등)
    'django.contrib.sessions.middleware.SessionMiddleware', # 요청 시 세션 로드, 응답 시 세션 저장.
    'django.middleware.common.CommonMiddleware',         # Disallowed Hosts 처리, URL 슬래시 자동 추가/제거 등.
    'django.middleware.csrf.CsrfViewMiddleware',         # CSRF(Cross-Site Request Forgery) 공격 방어. POST 요청 시 유효성 검사.
    'django.contrib.auth.middleware.AuthenticationMiddleware', # 요청 객체에 현재 로그인된 사용자(request.user)를 연결.
    'django.contrib.messages.middleware.MessageMiddleware', # 요청 객체에 메시지 프레임워크 연결 (request.messages).
    'django.middleware.clickjacking.XFrameOptionsMiddleware', # Clickjacking 방어를 위해 X-Frame-Options 헤더 설정.
]

# ==============================
# URL / TEMPLATE
# ==============================
# 프로젝트의 메인 URL 설정 파일 경로입니다.
# **동작 원리:** Django가 들어온 요청 URL을 이 파일에 정의된 패턴과 매칭시켜 적절한 View 함수를 찾습니다.
ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': 템플릿 파일을 찾을 추가 디렉토리 목록입니다. 앱 폴더 밖의 프로젝트 전역 템플릿을 위해 설정합니다.
        'DIRS': [BASE_DIR / 'templates'],
        # 'APP_DIRS': True일 경우, INSTALLED_APPS에 있는 각 앱 디렉토리 내의 'templates/' 폴더를 탐색합니다. (필수)
        'APP_DIRS': True,
        'OPTIONS': {
            # 'context_processors': 모든 템플릿 렌더링 시 자동으로 추가되는 컨텍스트 변수 목록입니다.
            'context_processors': [
                'django.template.context_processors.debug',    # DEBUG, sql_queries
                'django.template.context_processors.request',  # request 객체
                'django.contrib.auth.context_processors.auth', # user 객체, perms
                'django.contrib.messages.context_processors.messages', # messages 객체
            ],
        },
    },
]

# WSGI(Web Server Gateway Interface) 애플리케이션의 경로입니다.
# **동작 원리:** 실제 웹 서버(Gunicorn, uWSGI 등)가 Django 애플리케이션을 실행하기 위해 호출하는 진입점입니다.
WSGI_APPLICATION = 'config.wsgi.application'

# ==============================
# DATABASE (개발용 MySQL 또는 환경 변수 기반)
# ==============================
DATABASES = {
    "default": {
        # 환경 변수에 따라 데이터베이스 엔진을 결정합니다 (기본값: MySQL).
        "ENGINE": os.getenv("DB_ENGINE", "django.db.backends.mysql"),
        # 나머지 설정도 환경 변수에서 로드합니다.
        "NAME": os.getenv("DB_NAME", "bookmark"),
        "USER": os.getenv("DB_USER", "root"),
        "PASSWORD": os.getenv("DB_PASSWORD", ""),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "3306"),
        "OPTIONS": {
            "charset": os.getenv("DB_CHARSET", "utf8mb4"),
        },
    }
}
# **동작 원리:**
# - Django ORM(Object-Relational Mapper)은 이 설정에 따라 데이터베이스에 연결하고 SQL 쿼리를 실행합니다.
# - DB_ENGINE에 따라 적절한 데이터베이스 어댑터가 로드됩니다.

# ==============================
# PASSWORD VALIDATION
# ==============================
# 사용자 암호의 유효성을 검사하는 규칙들의 목록입니다.
# **동작 원리:**
# - User 생성 또는 암호 변경 시, 이 목록의 Validator들이 순서대로 실행됩니다.
# - 'UserAttributeSimilarityValidator': 암호가 사용자 이름이나 이메일과 너무 유사한지 검사.
# - 'MinimumLengthValidator': 암호의 최소 길이를 검사.
# - 'CommonPasswordValidator': 흔하게 사용되는 암호 목록에 포함되어 있는지 검사.
# - 'NumericPasswordValidator': 암호가 완전히 숫자로만 구성되어 있는지 검사.
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ==============================
# INTERNATIONALIZATION
# ==============================
# 언어, 시간대 및 현지화 설정입니다.
LANGUAGE_CODE = 'ko-KR' # 사이트의 기본 언어
TIME_ZONE = 'UTC'       # 서버의 기본 시간대 (DB 저장 시 UTC 사용 권장)
USE_I18N = True         # 국제화(i18n) 시스템 활성화 (다국어 지원)
USE_TZ = True           # 시간대 인식(Time-zone aware) datetime 활성화 (UTC 저장, 설정된 TIME_ZONE으로 변환 표시)

# ==============================
# STATIC FILES (🔥 여기 핵심)
# ==============================
# 정적 파일(static files, CSS/JS/Images)을 서빙할 때 사용되는 URL 접두사입니다.
# **동작 원리:**
# - 템플릿에서 `{% static 'path/to/file.css' %}`를 사용하면, 이 설정(STATIC_URL)과 합쳐져 `/static/path/to/file.css`와 같은 URL이 생성됩니다.
# - 개발 환경(DEBUG=True)에서는 Django가 이 URL을 처리하여 앱 내부의 `static/` 폴더에서 파일을 찾아서 서빙합니다.
STATIC_URL = '/static/'   # 🔥 반드시 슬래시 포함

# ❌ 개발 중에는 아래 둘 필요 없음 (운영 환경에서만 사용)
# STATIC_ROOT: collectstatic 명령으로 정적 파일이 복사되어 모이는 절대 경로 (운영 서버에서 Nginx/Apache 등이 서빙할 위치).
# STATICFILES_DIRS: 앱의 static/ 폴더 외에 추가적인 정적 파일 디렉토리를 지정할 때 사용.

# ==============================
# DEFAULT PK
# ==============================
# 모델을 만들 때 기본적으로 사용될 Primary Key 필드의 유형입니다.
# **동작 원리:**
# - Django 3.2+ 버전부터는 기본으로 BigAutoField(64비트 정수, 더 큰 값 허용)를 사용하도록 권장합니다.
# - 명시하지 않은 모든 모델의 `id` 필드가 이 유형으로 생성됩니다.
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
