# Generated by Django 6.0 on 2025-12-27 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_category_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created_at', '-id'), 'verbose_name': '댓글', 'verbose_name_plural': '댓글 목록'},
        ),
    ]
