# Generated by Django 6.0 on 2025-12-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"verbose_name": "블로그", "verbose_name_plural": "블로그 목록"},
        ),
        migrations.AlterField(
            model_name="blog",
            name="category",
            field=models.CharField(
                choices=[
                    ("FREE", "자유게시판"),
                    ("C", "C"),
                    ("PYTHON", "Python"),
                    ("JAVA", "Java"),
                    ("명령어", "Linux"),
                ],
                max_length=10,
                verbose_name="카테고리",
            ),
        ),
    ]
