# Generated by Django 6.0 on 2025-12-26 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blog_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="category",
            field=models.CharField(
                choices=[
                    ("FREE", "자유게시판"),
                    ("C", "C"),
                    ("PYTHON", "Python"),
                    ("JAVA", "Java"),
                    ("LINUX", "Linux 명령어"),
                ],
                default="free",
                max_length=10,
                verbose_name="카테고리",
            ),
        ),
    ]
