# Generated by Django 6.0 on 2025-12-28 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_at', '-id'), 'verbose_name': '댓글', 'verbose_name_plural': '댓글 목록'},
        ),
    ]
