# Generated by Django 6.0 on 2025-12-30 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='thubnail',
            field=models.ImageField(blank=True, null=True, upload_to='blog/%Y/%m/%d', verbose_name='썸네일'),
        ),
    ]
