# Generated by Django 6.0.1 on 2026-02-02 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='공부한 내용')),
                ('duration_minutes', models.IntegerField(help_text='공부 시간 (분)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 시간')),
            ],
            options={
                'verbose_name': '공부 내용',
                'verbose_name_plural': '공부 내용들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='스터디 제목', max_length=200)),
                ('goal', models.TextField(help_text='학습 목표')),
                ('start_at', models.DateTimeField(help_text='시작 시간')),
                ('end_at', models.DateTimeField(help_text='종료 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 시간')),
            ],
            options={
                'verbose_name': '스터디 이벤트',
                'verbose_name_plural': '스터디 이벤트들',
                'ordering': ['-start_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, help_text='타이머 시작 시간', null=True)),
                ('ended_at', models.DateTimeField(blank=True, help_text='타이머 종료 시간', null=True)),
                ('total_minutes', models.IntegerField(default=0, help_text='총 공부 시간 (분)')),
                ('is_running', models.BooleanField(default=False, help_text='타이머 실행 중 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 시간')),
            ],
            options={
                'verbose_name': '스터디 타이머',
                'verbose_name_plural': '스터디 타이머들',
                'ordering': ['-created_at'],
            },
        ),
    ]
