# Generated by Django 6.0.1 on 2026-02-02 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('study', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studyevent',
            name='user',
            field=models.ForeignKey(help_text='스터디 소유자', on_delete=django.db.models.deletion.CASCADE, related_name='study_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studycontent',
            name='study_event',
            field=models.ForeignKey(help_text='연관된 스터디 이벤트', on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='study.studyevent'),
        ),
        migrations.AddField(
            model_name='studytimer',
            name='study_event',
            field=models.ForeignKey(help_text='연관된 스터디 이벤트', on_delete=django.db.models.deletion.CASCADE, related_name='timers', to='study.studyevent'),
        ),
    ]
