# Generated by Django 6.0.1 on 2026-02-02 04:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(help_text='사용자 아이디 (로그인용, 고유값, 최대 150자)', max_length=150, unique=True)),
                ('email', models.EmailField(help_text='이메일 주소 (고유값, 이메일 형식 검증 자동 수행)', max_length=254, unique=True)),
                ('nickname', models.CharField(blank=True, help_text='닉네임 (프로필 별명, 비워둘 수 있음, 최대 50자)', max_length=50)),
                ('bio', models.TextField(blank=True, help_text='자기소개 (프로필 메시지, 비워둘 수 있음, 텍스트 길이 제한 없음)')),
                ('profile_image', models.ImageField(blank=True, help_text='프로필 이미지 (MEDIA_ROOT/profiles/ 경로에 저장, 비워둘 수 있음)', null=True, upload_to='profiles/')),
                ('email_verified', models.BooleanField(default=False, help_text='이메일 인증 여부 (True: 인증 완료, False: 미인증, 기본값: False)')),
                ('email_verification_code', models.CharField(blank=True, help_text='이메일 인증 코드 (6자리 숫자, 인증 완료 후 None으로 변경)', max_length=6, null=True)),
                ('email_verification_code_expires_at', models.DateTimeField(blank=True, help_text='인증 코드 만료 시간 (Datetime 객체, 만료 후 None으로 변경)', null=True)),
                ('biometric_enabled', models.BooleanField(default=False, help_text='생체인식 로그인 활성화 여부 (True: 사용, False: 미사용, 기본값: False)')),
                ('device_token', models.CharField(blank=True, help_text='기기 토큰 (Push 알림 또는 기기 고유 식별자, 비워둘 수 있음, 최대 255자)', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='계정 활성화 여부 (True: 활성, False: 비활성/정지, 기본값: True)')),
                ('is_staff', models.BooleanField(default=False, help_text='스태프(관리자페이지 접근권한) 여부 (True: Django Admin 접근 가능, 기본값: False)')),
                ('is_superuser', models.BooleanField(default=False, help_text='슈퍼유저(전체 권한) 여부 (True: 모든 권한 보유, 기본값: False)')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, help_text='가입일 (자동 기록, timezone.now()로 현재 시간 저장)')),
                ('last_login', models.DateTimeField(blank=True, help_text='마지막 로그인 일시 (자동 기록, 비워둘 수 있음, 로그인 시 업데이트)', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자들',
                'db_table': 'users',
            },
        ),
    ]
