# Generated by Django 6.0.1 on 2026-02-02 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='biometric_enabled',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='device_token',
        ),
    ]
