# Generated by Django 6.0.1 on 2026-02-03 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_biometric_enabled_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-date_joined'], 'verbose_name': '사용자', 'verbose_name_plural': '사용자들'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='이메일 주소 (로그인용, 고유값, 이메일 형식 검증 자동 수행)', max_length=254, unique=True),
        ),
    ]
