"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv  # ✅ .env 파일을 읽어 환경변수로 올려주는 라이브러리
import os

# ==============================
# 0) settings.py의 정체
# ==============================
# ✅ Django 프로젝트 설정의 "실행되는 파이썬 코드"
# - manage.py runserver 실행 시, Django가 이 파일을 import 해서 한 줄씩 실행합니다.
# - 즉, 여기서 정의한 값들은 Django의 전역 설정 객체(settings)에 저장되어
#   요청 처리, 템플릿 렌더링, DB 연결, 보안 검사 등에 사용됩니다.

# ==============================
# 1) BASE_DIR
# ==============================
# ✅ 프로젝트 루트 디렉토리 경로
# - Path(__file__) : 현재 파일(settings.py) 경로 객체
# - resolve()      : 상대경로/심볼릭링크를 풀어서 "절대경로"로 고정
# - parent.parent  : config/settings.py 기준으로 2단계 위(프로젝트 루트)
#
# 🔥 동작 원리
# - Django 설정에서 파일 경로를 지정할 때 "기준점"으로 사용합니다.
# - 예) BASE_DIR / ".env", BASE_DIR / "templates" 같은 식으로 안전하게 경로를 만듦
BASE_DIR = Path(__file__).resolve().parent.parent

# ==============================
# 2) ENV LOAD (.env 로딩)
# ==============================
# ✅ .env 파일을 읽어서 환경변수(os.environ)에 등록
#
# 🔥 동작 원리 (중요)
# 1) load_dotenv가 BASE_DIR/.env 파일을 읽음
# 2) 내부적으로 KEY=VALUE 를 파싱해서
#    os.environ["KEY"] = "VALUE" 형태로 환경 변수에 올립니다.
# 3) 그 다음부터는 Python 어디서든 os.getenv("KEY") 로 접근 가능
#
# override=True
# - 이미 OS에 설정된 환경변수가 있더라도 .env 값으로 덮어씀
# - 개발 환경에서는 편하지만, 운영에서는 보통 False를 선호하기도 함(정책에 따라)
load_dotenv(dotenv_path=str(BASE_DIR / ".env"), override=True)

# ==============================
# 3) SECRET_KEY
# ==============================
# ✅ Django 보안의 핵심 키
#
# 🔥 동작 원리
# - 세션 쿠키/서명(Signing), CSRF 토큰, 패스워드 리셋 토큰 등
#   "서명/암호화/무결성" 기능에 사용되는 비밀값입니다.
#
# ⚠️ 중요한 특징
# - SECRET_KEY가 바뀌면:
#   - 기존 세션/토큰들이 전부 무효가 될 수 있음 (로그인 풀림, 토큰 깨짐)
# - 운영 환경에서는 하드코딩 금지 (환경변수로만 관리)
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-temp-key",  # ✅ 개발/학습용 fallback (운영에서는 절대 사용 금지)
)

# ==============================
# 4) DEBUG
# ==============================
# ✅ 개발 모드 여부
#
# 🔥 동작 원리
# - True:
#   - 에러가 나면 디버그 페이지(스택트레이스, 설정값 일부 등) 노출
#   - 개발 서버에서 static을 편하게 서빙
#   - 개발에 유용한 기능 활성화
# - False:
#   - 에러 상세정보 숨김(보안)
#   - ALLOWED_HOSTS 검사 강제
#   - 운영 환경에 맞는 동작으로 전환
DEBUG = True

# ==============================
# 5) ALLOWED_HOSTS
# ==============================
# ✅ 허용할 Host 헤더 목록 (도메인/IP)
#
# 🔥 동작 원리
# - DEBUG=False 일 때 Django가 요청의 Host 헤더를 검사합니다.
# - 요청 Host가 이 리스트에 없으면 "400 Bad Request"로 차단
# - 목적: Host Header Attack 방어
#
# 예)
# ALLOWED_HOSTS = ["localhost", "127.0.0.1", "mydomain.com"]
ALLOWED_HOSTS = []

# ==============================
# 6) INSTALLED_APPS
# ==============================
# ✅ Django가 "어떤 앱들을 로드할지" 결정하는 목록
#
# 🔥 동작 원리 (서버 시작 시)
# 1) Django가 INSTALLED_APPS를 순회하며 앱 설정(AppConfig)을 로드
# 2) 각 앱의 models.py를 찾아 모델 등록
# 3) admin.py 등록
# 4) migrations 적용 대상 인식
# 5) 템플릿 로더(APP_DIRS=True) 사용 시 앱 내부 templates/를 자동 검색
#
# ✅ 기본 제공 앱(DJANGO_APPS)
DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",  # 🔥 admin 페이지 css/js도 여기서 처리됨
]

# ✅ 내가 만든 앱(OWN_APPS)
OWN_APPS = [
    "blog",
    "member"
    
]

# ✅ 외부 라이브러리 앱(THIRD_PARTY_APPS)
# - 예: django_extensions는 shell_plus, runscript 같은 개발 편의 기능 제공
THIRD_PARTY_APPS = [
    "django_extensions"
]

# ✅ 최종 앱 등록
# (리스트끼리 더하면 하나의 리스트로 합쳐짐)
INSTALLED_APPS = DJANGO_APPS + OWN_APPS + THIRD_PARTY_APPS

# ==============================
# 7) MIDDLEWARE
# ==============================
# ✅ 요청(Request)과 응답(Response) 사이에 끼어드는 처리 파이프라인
#
# 🔥 동작 원리 (진짜 중요)
# - Request 들어올 때: 위 → 아래 순서로 실행
# - Response 나갈 때: 아래 → 위 역순으로 실행
#
# 예시 흐름
# 브라우저 요청 → Security → Session → Common → CSRF → Auth → Messages → Clickjacking → view → 응답
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",        # 보안 헤더, HTTPS 관련 설정 지원
    "django.contrib.sessions.middleware.SessionMiddleware", # request.session 사용 가능하게 세션 로드/저장
    "django.middleware.common.CommonMiddleware",            # URL 슬래시 처리, 기타 공통 기능
    "django.middleware.csrf.CsrfViewMiddleware",            # POST/PUT 등에서 CSRF 토큰 검증
    "django.contrib.auth.middleware.AuthenticationMiddleware", # request.user 붙여줌
    "django.contrib.messages.middleware.MessageMiddleware", # messages 프레임워크
    "django.middleware.clickjacking.XFrameOptionsMiddleware", # iframe 악용(클릭재킹) 방어
]

# ==============================
# 8) ROOT_URLCONF
# ==============================
# ✅ "최상위 URL 라우팅 테이블" 위치
#
# 🔥 동작 원리
# - Django는 요청 URL이 들어오면 settings.ROOT_URLCONF에 지정된 모듈을 import 합니다.
# - 그 안의 urlpatterns를 위에서부터 매칭해서 실행할 view를 결정합니다.
ROOT_URLCONF = "config.urls"

# ==============================
# 9) TEMPLATES
# ==============================
# ✅ 템플릿(HTML) 렌더링 규칙
#
# 🔥 동작 원리
# - render(request, "blog_list.html", context)를 호출하면:
#   1) 템플릿 엔진이 파일을 찾음
#   2) context + context_processors 결과를 합침
#   3) {{ }}와 {% %} 를 렌더링해 HTML 문자열 생성
#
# DIRS
# - 프로젝트 전역 템플릿 위치 (BASE_DIR/templates)
#
# APP_DIRS=True
# - INSTALLED_APPS에 등록된 각 앱의 templates/ 폴더도 자동 검색
#
# context_processors
# - 모든 템플릿에 자동으로 들어가는 기본 변수들
#   - request, user, messages 등
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",       # DEBUG 관련 변수 제공
                "django.template.context_processors.request",     # request를 템플릿에 주입
                "django.contrib.auth.context_processors.auth",    # user, perms 주입
                "django.contrib.messages.context_processors.messages", # messages 주입
            ],
        },
    },
]

# ==============================
# 10) WSGI_APPLICATION
# ==============================
# ✅ 배포(운영)에서 웹서버가 Django 앱을 실행하는 진입점
#
# 🔥 동작 원리
# - gunicorn/uwsgi 같은 WSGI 서버가 이 경로를 import 해서 application 객체를 얻고,
#   그걸 통해 Django에 요청을 전달합니다.
# - 개발(runserver)에서는 내부 서버가 대신 해줌.
WSGI_APPLICATION = "config.wsgi.application"

# ==============================
# 11) DATABASES
# ==============================
# ✅ Django ORM이 DB에 연결하는 방법
#
# 🔥 동작 원리
# - Blog.objects.all() 같은 ORM 호출이 발생하면:
#   1) Django가 DATABASES["default"] 설정을 보고 연결 생성
#   2) ENGINE에 맞는 DB 드라이버/백엔드 로드
#   3) SQL 생성 후 실행
#
# ENGINE에 따라 필요한 패키지가 달라짐
# - MySQL: mysqlclient (보통)
# - PostgreSQL: psycopg 등
DATABASES = {
    "default": {
        "ENGINE": os.getenv("DB_ENGINE", "django.db.backends.mysql"),
        "NAME": os.getenv("DB_NAME", "bookmark"),
        "USER": os.getenv("DB_USER", "root"),
        "PASSWORD": os.getenv("DB_PASSWORD", ""),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "3306"),
        "OPTIONS": {
            "charset": os.getenv("DB_CHARSET", "utf8mb4"),
        },
    }
}

# ==============================
# 12) AUTH_PASSWORD_VALIDATORS
# ==============================
# ✅ 비밀번호 정책(검사 규칙)
#
# 🔥 동작 원리
# - 사용자가 비밀번호를 설정/변경할 때:
#   Django가 이 목록을 순서대로 실행해서 규칙 위반 여부를 검사합니다.
# - 위반하면 ValidationError 발생 → 가입/변경 실패
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ==============================
# 13) INTERNATIONALIZATION / TIMEZONE
# ==============================
# ✅ 언어/시간대/현지화 설정
#
# 🔥 동작 원리
# - USE_TZ=True 이면:
#   - DB에는 기본적으로 UTC로 저장
#   - 화면에 표시할 때 TIME_ZONE 기준으로 변환해서 보여줌
#
# ⚠️ 현재 TIME_ZONE="UTC"라서 한국 시간으로 보고 싶으면:
# TIME_ZONE = "Asia/Seoul" 로 바꾸면 됨
LANGUAGE_CODE = "ko-KR"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# ==============================
# 14) STATIC_URL (정적 파일)
# ==============================
# ✅ CSS/JS/이미지 같은 정적 파일을 어떤 URL로 제공할지
#
# 🔥 동작 원리 (개발환경)
# - DEBUG=True일 때:
#   Django 개발 서버가 /static/ 요청을 받아서
#   각 앱의 static/ 폴더에서 파일을 찾아 응답합니다.
#
# 템플릿에서:
# {% load static %}
# <link rel="stylesheet" href="{% static 'css/style.css' %}">
# =>
# /static/css/style.css 로 변환됨 (STATIC_URL + 경로)
STATIC_URL = "/static/"

# ==============================
# 15) DEFAULT_AUTO_FIELD
# ==============================
# ✅ 모델에서 id(pk)를 따로 정의하지 않았을 때, 기본 PK 타입을 무엇으로 할지
#
# 🔥 동작 원리
# - 모델에 id 필드를 직접 만들지 않으면 Django가 자동으로 만들어줍니다.
# - 그 자동 생성 규칙이 DEFAULT_AUTO_FIELD 입니다.
#
# BigAutoField란?
# - 64비트 정수 자동 증가 (더 큰 범위를 커버)
# - 데이터가 많아져도 PK가 고갈될 위험이 줄어듦
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

#login
LOGIN_REDIRECT_URL = '/'
LOGIN_URL = '/login/'
LOGOUT_REDIRECT_URL = '/'
