# Generated by Django 6.0.1 on 2026-02-02 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='일정 제목', max_length=200)),
                ('description', models.TextField(blank=True, help_text='일정 설명')),
                ('start_at', models.DateTimeField(help_text='시작 시간')),
                ('end_at', models.DateTimeField(help_text='종료 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 시간')),
            ],
            options={
                'verbose_name': '일정',
                'verbose_name_plural': '일정들',
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='과목명', max_length=100)),
                ('exam_date', models.DateField(help_text='시험 날짜')),
                ('score', models.IntegerField(blank=True, help_text='점수 (시험 전에는 None)', null=True)),
                ('max_score', models.IntegerField(help_text='만점')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 시간')),
            ],
            options={
                'verbose_name': '시험',
                'verbose_name_plural': '시험들',
                'ordering': ['exam_date'],
            },
        ),
        migrations.CreateModel(
            name='RepeatEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='반복 일정 제목', max_length=200)),
                ('description', models.TextField(blank=True, help_text='반복 일정 설명')),
                ('start_at', models.DateTimeField(help_text='시작 시간')),
                ('end_at', models.DateTimeField(help_text='종료 시간')),
                ('rule', models.CharField(help_text='RRULE 반복 규칙 (예: FREQ=DAILY;INTERVAL=1)', max_length=500)),
                ('until', models.DateField(help_text='반복 종료일')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 시간')),
            ],
            options={
                'verbose_name': '반복 일정',
                'verbose_name_plural': '반복 일정들',
                'ordering': ['start_at'],
            },
        ),
    ]
