# Generated by Django 6.0.1 on 2026-02-02 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(help_text='일정 소유자', on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='user',
            field=models.ForeignKey(help_text='시험 소유자', on_delete=django.db.models.deletion.CASCADE, related_name='exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repeatevent',
            name='user',
            field=models.ForeignKey(help_text='반복 일정 소유자', on_delete=django.db.models.deletion.CASCADE, related_name='repeat_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
